### ISSUE TITLE
Only 3 features showing on download single

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/theme2016#13]
I am editing the Gantt addon and made 5 features. Only 3 show on the frontend.

**Comment by brashrebel** [comment]
Possibly related. When I added the features, the requirements section disappeared.

**Comment by d4mation** [comment]
It is showing 5 for me on the Live site currently for Gantt. Maybe it has corrected itself?

![image](https://cloud.githubusercontent.com/assets/7770631/17228845/e51f093c-54e2-11e6-89f3-4c0086c02722.png)

**Comment by d4mation** [comment]
The Requirements aren't showing due to the page not being able to scroll enough for them to trigger their entering animation.

This _should_ get fixed with #17 as that will give us more vertical movement.

**Comment by d4mation** [comment]
Now that we have the Footer and the Alternate Buy button from #20, these problems seem to have been fixed.

**Comment by brashrebel** [comment]
On my vertical monitor, I still can't get anything past the 3 features to load.

**Comment by d4mation** [comment]
Ah, it is probably your portrait monitor causing the problems.

The JavaScript for the transitions checks if the content has hit a certain percentage up the page before it begins its transition into view. The portrait monitor shows so much at once that it could be causing problems.

I could try to adjust the percentage to see if another value works better for you or we could remove the transitions. I can try to replicate it in the Chrome Device Emulator in a bit. I'm adding more padding for #12.

**Comment by brashrebel** [comment]
I guess the transitions are not _really_ important. We should probably consider that a flourish to add rather than get hung up on it now while there's so much else to do.
